django_form_architect/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('django_form_architect.views', 
    url(r'^$', 'home'),
    url(r'^fill-out/(?P<id>\d+)/$', 'fill_out'),
    url(r'^new/$', 'build'),
    url(r'^edit/(?P<id>\d+)/$', 'build'), 
    url(r'^share/(?P<id>\d+)/$', 'share'),
)

django_form_architect/models.py
from django.db import models
from polymorphic import PolymorphicModel
import json


def add_options(model, option_list, group='options'):
    cnt = 0
    for option in option_list:
        new_option = WidgetOption();
        new_option.text = option.get('text', None)
        new_option.selected = bool(option.get('selected', False))
        new_option.sequence = cnt
        new_option.selection_group = group
        
        cnt += 1
        model.options.add(new_option)   

class Form(models.Model):    
    pid = models.AutoField(primary_key=True)
    slug = models.SlugField(help_text='This is the url endpoint')
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_active = models.BooleanField(default=True, help_text='The endpoint will work only if this is true.')
    
    def json_serialize(self):
        return json.dumps({
            'pid' : self.pid,
            'slug' : self.slug,
            'name' : self.name,
            'title' : self.title,
            'description' : self.description,
            'is_active' : self.is_active
        })
    
    def __str__(self):
        return self.__unicode__()
    
    def __unicode__(self):
        return "endpoint:  {0} active: {1}".format(self.slug, self.is_active)
 
class Page(models.Model):
    pid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    sequence = models.IntegerField(default=0)
    form= models.ForeignKey(Form)
     
    def active_widgets(self):
        return self.widget_set.filter(is_active=True)
     
    def json_serialize(self):
        return json.dumps({
            'pid': self.pid,
            'name': self.name,
            'sequence': self.sequence
        })
     
    class Meta:    
        ordering = ('sequence',)     
         
class Widget(PolymorphicModel):
    pid = models.AutoField(primary_key=True)
    form = models.ForeignKey(Form)
    label = models.CharField(max_length=100, null=True)
    help_text = models.CharField(max_length=100, null=True)
    required = models.BooleanField()
    sequence = models.IntegerField(default=0)
    page = models.ForeignKey(Page, null=True, default=None)
    is_active = models.BooleanField(default=True)
    
    @property
    def class_name(self):
        return self.__class__.__name__
    
    def to_dict(self):
        return {
            'pid': self.pid,
            'label': self.label,
            'help_text': self.help_text,
            'required': self.required,
            'sequence': self.sequence
        }
    
    def from_dict(self, dict):
        if dict.get('pid', None):
            self.pid = dict['pid']
        self.label = dict.get('label', None)
        self.help_text = dict.get('help_text', None)
        self.required = bool(dict.get('required', False))
        self.sequence = dict.get('sequence', 0)        

    class Meta:    
        ordering = ('sequence',)
        

class WidgetOption(models.Model):
    SELECTION_GROUPS = (
        ('options', 'options'),
        ('rows', 'rows'),
        ('columns', 'columns'),
    )
    
    text = models.CharField(max_length=50)
    selected = models.BooleanField()
    widget = models.ForeignKey(Widget)
    sequence = models.IntegerField(default=0)
    selection_group = models.CharField(max_length=10, choices=SELECTION_GROUPS, default='options')
            
    def json_serialize(self):
        return {
            'text': self.text,
            'selected': self.selected,
            'sequence': self.sequence,
            'selection_group': self.selection_group,            
        }        
    
    class Meta:    
        ordering = ('sequence',)
            
class TextBoxWidget(Widget):
    SIZES = (
        ('s', 'small'),
        ('m', 'medium'),
        ('l', 'large'),
    )
    
    default = models.CharField(max_length=100, null=True)
    size = models.CharField(max_length=1, choices=SIZES)
    
    def from_dict(self, dict, *args, **kwargs):        
        super(TextBoxWidget, self).from_dict(dict)
        self.default = dict.get('default', None)
        self.size = dict.get('size', None)
                
    def json_serialize(self):        
        dict = super(TextBoxWidget, self).to_dict()
        dict.update({
            'default': self.default,
            'size': self.size
        })
        
        return json.dumps(dict) 
    
class TextAreaWidget(Widget):
    SIZES = (
        ('s', 'small'),
        ('m', 'medium'),
        ('l', 'large'),
    )
    
    CONTENT_TYPES = (
        ('text', 'text'),
        ('richtext', 'rich text'),        
    )
    
    default = models.TextField(null=True)
    size = models.CharField(max_length=1, choices=SIZES)
    content_type = models.CharField(max_length=10, choices=CONTENT_TYPES)
    
    def from_dict(self, dict, *args, **kwargs):
        super(TextAreaWidget, self).from_dict(dict)
        self.default = dict.get('default', None)
        self.size = dict.get('size', None)
        self.content_type = dict.get('content_type', None)        
        
    def json_serialize(self):        
        dict = super(TextAreaWidget, self).to_dict()
        dict.update({
            'default': self.default,
            'size': self.size,
            'content_Type': self.content_type
        })
        
        return json.dumps(dict) 

class CheckBoxWidget(Widget):
    @property
    def options(self):
        return self.widgetoption_set
    
    def from_dict(self, dict, *args, **kwargs):
        super(CheckBoxWidget, self).from_dict(dict)
        
        if self.pid:
            self.options.all().delete()
        else:
            form = kwargs['form']        
            form.widget_set.add(self)
        
        add_options(self, dict.get('options', []))        
        
    def json_serialize(self):        
        dict = super(CheckBoxWidget, self).to_dict()        
        option_dicts = []
        for option in self.options.all():
            option_dicts.append(option.json_serialize())
            
        dict.update({
            'options': option_dicts,            
        })
        
        return json.dumps(dict) 

class DropDownWidget(Widget):
    SIZES = (
        ('s', 'small'),
        ('m', 'medium'),
        ('l', 'large'),
    )
    
    size = models.CharField(max_length=1, choices=SIZES, default='m')
    
    @property
    def options(self):
        return self.widgetoption_set
    
    def from_dict(self, dict, *args, **kwargs):
        super(DropDownWidget, self).from_dict(dict)
        self.size = dict.get('size', 'm')
        
        if self.pid:
            self.options.all().delete()
        else:
            form = kwargs['form']        
            form.widget_set.add(self)
        
        add_options(self, dict.get('options', []))                  
        
    def json_serialize(self):        
        dict = super(DropDownWidget, self).to_dict()        
        option_dicts = []
        for option in self.options.all():
            option_dicts.append(option.json_serialize())
            
        dict.update({
            'options': option_dicts,   
            'size': self.size,         
        })
        
        return json.dumps(dict)     

class SelectionTableWidget(Widget):
    
    @property
    def options(self):
        return self.widgetoption_set
    
    @property
    def rows(self):
        return self.options.filter(selection_group='rows')
    
    @property
    def columns(self):
        return self.options.filter(selection_group='options')
    
    def from_dict(self, dict, *args, **kwargs):
        super(SelectionTableWidget, self).from_dict(dict)
                
        if self.pid:
            self.options.all().delete()
        else:
            form = kwargs['form']        
            form.widget_set.add(self)
        
        add_options(self, dict.get('rows', []), group='rows')
        add_options(self, dict.get('options', []), group='options')                  
        
    def json_serialize(self):        
        dict = super(SelectionTableWidget, self).to_dict()        
        row_dicts = []
        for row in self.rows.all():
            row_dicts.append(row.json_serialize())
            
        column_dicts = []
        for column in self.columns.all():
            column_dicts.append(column.json_serialize())
            
        dict.update({
            'rows': row_dicts,
            'options': column_dicts,
        })
        
        return json.dumps(dict) 

class SectionBreakWidget(Widget):    
    
    def from_dict(self, dict, *args, **kwargs):        
        super(SectionBreakWidget, self).from_dict(dict)
                        
    def json_serialize(self):        
        dict = super(SectionBreakWidget, self).to_dict()
        return json.dumps(dict) 
    
class RadioButtonWidget(Widget):
    @property
    def options(self):
        return self.widgetoption_set
    
    def from_dict(self, dict, *args, **kwargs):
        super(RadioButtonWidget, self).from_dict(dict)
        
        if self.pid:
            self.options.all().delete()
        else:
            form = kwargs['form']        
            form.widget_set.add(self)
        
        add_options(self, dict.get('options', []))        
        
    def json_serialize(self):        
        dict = super(RadioButtonWidget, self).to_dict()        
        option_dicts = []
        for option in self.options.all():
            option_dicts.append(option.json_serialize())
            
        dict.update({
            'options': option_dicts,            
        })
        
        return json.dumps(dict) 
    
class PhoneNumberWidget(Widget):
    
    default = models.CharField(max_length=100, null=True)
    mask = models.CharField(max_length=50)
    
    def from_dict(self, dict, *args, **kwargs):        
        super(PhoneNumberWidget, self).from_dict(dict)
        self.default = dict.get('default', None)

django_form_architect/templates/django_form_architect/base.html
<!DOCTYPE HTML>
<html lang='en'>
	<head>
		<title>{% block title %}Django Form Architect{% endblock %}</title>
		<link href='{{ STATIC_URL }}django_form_architect/css/base.css' rel='stylesheet' type='text/css' media='screen' />
		<link href='{{ STATIC_URL }}django_form_architect/css/font-awesome.css' rel='stylesheet' type='text/css' media='screen' />
	</head>
	<body>
		<div id='main-container'>
			<div id='nav-wrapper'>
				<ul id='nav'>
					<li><a href='{% url 'django_form_architect.views.home' %}'><i class='icon-home'></i>home</a></li>
					<li><a href='{% url 'django_form_architect.views.build' %}'><i class='icon-plus'></i>new form</a></li>
					<li><a href='{% url 'django_form_architect.views.build' %}'><i class='icon-file-text-alt'></i>reports</a></li>
					<li><a href='{% url 'django_form_architect.views.build' %}'><i class='icon-user'></i>users</a></li>
				</ul>
				<div style='clear:both;'></div>				
			</div>
			<div id='main-content-positioner'>
				<div id='main-content-background'>
					<div id='main-content-wrap'>
						<div id='main-content'>				
							{% block content %}
							{% endblock %}
						</div>
					</div>
					<div id='footer-wrap'>
						<div id='footer'>
							<span class='branding'>Django Form Admin</span>
						</div>
					</div>
				</div>
			</div>			
		</div> 
		
		{% block javascript %}
			<script src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
			<script src='//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js'></script>
		{% endblock %}				
	</body>
</html>

django_form_architect/templates/django_form_architect/embed_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang='en'>
	<head>
		<title>{% block title %}Django Form Architect{% endblock %}</title>
		<link href='{{ STATIC_URL }}django_form_architect/css/embedded_host.css' rel='stylesheet' type='text/css' media='screen' />
		<link href='{{ STATIC_URL }}django_form_architect/css/default_formstyles.css' rel='stylesheet' type='text/css' media='screen' />
		<link href='{{ STATIC_URL }}django_form_architect/css/font-awesome.css' rel='stylesheet' type='text/css' media='screen' />
	</head>
	<body>
		<div id='main-container'>
			<div id='nav-wrapper'>
				<ul id='nav'>
					<li><a href='{% url 'django_form_architect.views.home' %}'><i class='icon-home'></i>home</a></li>
					<li><a href='{% url 'django_form_architect.views.build' %}'><i class='icon-plus'></i>new form</a></li>
					<li><a href='{% url 'django_form_architect.views.build' %}'><i class='icon-file-text-alt'></i>reports</a></li>
					<li><a href='{% url 'django_form_architect.views.build' %}'><i class='icon-user'></i>users</a></li>
				</ul>
				<div style='clear:both;'></div>				
			</div>
			<div id='form-wrapper'>								
				{% block content %}
				{% endblock %}				
			</div>			
		</div> 
		
		{% block javascript %}
			<script src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
			<script src='//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js'></script>
		{% endblock %}				
	</body>
</html>

django_form_architect/templates/django_form_architect/fill_out.html
{% extends 'django_form_architect/embed_base.html' %}

{% block content %}
	<div id="columns">
		<form method='POST' action='.'>
			{% csrf_token %} 
			
			{% if generated_form.errors %}
				<ul class="form-errors">
					<li class="error-header">
						<i class='icon-remove'></i>		
						there was an error on the current page					
					</li>		
				</ul>
			{% endif %}
			
			<div>
				{% for bound_field in generated_form %}
					{% include bound_field.field.template_path with bound_field=bound_field %}				
				{% endfor %}
			</div>
			
			<input type='submit' value='submit' />
		</form>
	</div>
{% endblock %}

django_form_architect/templates/django_form_architect/form_builder.html
{% extends 'django_form_architect/base.html' %}
{% load jsrender %}

{% block javascript %}
	{{ block.super }}
	<script src='{{ STATIC_URL }}django_form_architect/js/tinymce/tinymce.min.js'></script>
	<script src='{{ STATIC_URL }}django_form_architect/js/jsrender.min.js'></script>
	<script src='{{ STATIC_URL }}django_form_architect/js/jquery.maskedinput.min.js'></script>
	<script src='{{ STATIC_URL }}django_form_architect/js/utility.js'></script>
	<script src='{{ STATIC_URL }}django_form_architect/js/ui.js'></script>
	<script src='{{ STATIC_URL }}django_form_architect/js/form-builder.js'></script>
	
	{% for key, widget in widget_descriptors.items %}
		<script src='{{ widget.builder_js }}'></script>
	{% endfor %}
	
	<script>
		$(function() {
			window.dfb_globals = {};
			
			dfb_globals.form_settings = new dfb.FormSettings({% if form %}{{form.json_serialize|safe}}{% endif %});
			dfb_globals.context_menu = new dfb.ContextMenu();
			dfb_globals.builder = new dfb.FormBuilder({% if form %}{{form.json_serialize|safe}}{% endif %});
			dfb_globals.element_selector = new dfb.ElementSelector();
						
			{% for key, widget in widget_descriptors.items %}
				dfb.WidgetTypes.add('{{key}}', new dfb.WidgetType({					
					name: '{{widget.name}}',
					klass: '{{widget.js_klass}}'				
				}));
			{% endfor %}
			
			$('#form-settings-container').html(dfb_globals.form_settings.render('#form-settings-template'));
			$('#context-menu-container').html(dfb_globals.context_menu.render('#context-menu-template'));
			$('#form-builder-container').html(dfb_globals.builder.render('#form-builder-template'));
			$('#element-selector-container').html(dfb_globals.element_selector.render('#element-selector-template'));
			dfb_globals.left_menu_accordian = new dfb.ui.AccordianGroup({
				members: [$('#form-settings-header'), $('#context-menu-header'), $('#element-selector-header')],
			});
			dfb_globals.left_menu_accordian.onShow('context-menu', function() {
				dfb_globals.context_menu.positionMenuAtActive();
			});
			dfb_globals.left_menu_accordian.showByTag('element-selector');
			var widget = null;
			
			var first_page = null;
			{% for page in form.page_set.all %}
				var page = dfb_globals.builder.addPage({{page.json_serialize|safe}});								
				page.showPage();	
				{%if forloop.first %}
					first_page = page;				
				{% endif %}
				{% for widget in page.active_widgets %}
					dfb_globals.builder.addWidget(dfb.WidgetTypes.get('{{widget.class_name}}').settings.klass, dfb.WidgetTypes.get('{{widget.class_name}}').settings.template, {{widget.json_serialize|safe}});
				{% endfor %}
			{% empty %}
				var page = dfb_globals.builder.addPage({
					pid: null,
					name: 'page 1',
					selected: true
				});
				first_page = page;
			{% endfor %}				
			first_page.showPage();
			
		});
	</script>
{% endblock %}

{% block content %}
	<div class='wide-column'>
		<div id='form-settings-container'>
		</div>		
		<div id='element-selector-container'>		
		</div>				
		<div id='context-menu-container'>		
		</div>
	</div>
	<div class='main-column formbuilder'>
		<div id='form-builder-container'>		
		</div>						
	</div>
	
	<div style='clear:both;'></div>
	
		{% jsrender form-settings-template %}
			<div id='form-settings'>
				<div id='form-settings-header' class='accordian-header' data-tag='form-settings-menu' data-accordian-content-selector='#form-settings .settings-wrap'>
					change form settings
				</div>
				<div class='settings-wrap'>
					<div class='setting-group'>
						<div class='setting'>
							<label>name</label>
							<input type='text' id='form-name' maxlength='50' />
						</div>
					</div>					
				</div>
			</div>
		{% endjsrender %}
	
		<!-- pretty much all the work is done by javascript templates below -->
		{% jsrender context-menu-template %}
			<div id='context-menu'>
				<div id='context-menu-header' class='accordian-header' data-tag='context-menu' data-accordian-content-selector='#context-menu .slide-wrap'>
					currently editing 
				</div>
				<div class='slide-wrap'>
					<div class='slide jq-slide'>
						<div class='right-arrow'></div>
						<div class='jq-slide-content'></div>
					</div>
				</div>
			</div>
		{% endjsrender %}
		
		
		{% jsrender form-builder-template %}
			<div id='form-builder'>
				<input id='form-pid' type='hidden' value='{{:pid}}' />
								
				<div id='form-title' class='jq-form-title form-title'>	
					{{if title}}
						{{:title}}
					{{else}}
						No form header.  Click to set or remove.						
					{{/if}}										
				</div>
				<div id='form-description' class='jq-form-description form-description'>	
					{{if description}}
						{{:description}}
					{{else}}
						<p>
							No form description.  This is meant to be an intro paragraph describing how you want the form filled out, what will happen after you fill out the form, etc.<br />
							<br />  
							Click here to set the description or remove it entirely.
						</p>
					{{/if}}  
				</div>
				<div id='pagination-tabs'>										
					<div class='jq-add-page add-page'>
						<i class='icon-plus'></i>
					</div>
				</div>
				<div id='pagination-settings'>
					<div class='collapsed toggle jq-toggle'><i class='icon-chevron-down'></i>page settings</div>
					<i class='icon-remove-sign jq-delete-page'></i>
					<div class='settings jq-settings' style='display:none;'>
						<label>Page name</label><input type='text' id='page-name' class='jq-page-name' />
					</div>
				</div>
				<div id='form-builder-fields' class='element-selector-receiver'></div>
				<div class='control-separator'></div>
				<div class='buttons'>
					<a href='#' id='save-button' class='button'><i class='icon-upload'></i><span>save</span></a>
				</div>
			</div>
		{% endjsrender %}
		
		{% jsrender widget-page %}
			<div class='page{{if selected}} selected{{/if}}'>
				{{>name}}
			</div>
		{% endjsrender %}
		
		{% jsrender element-selector-template %}
			<div id='element-selector'>
				<div id='element-selector-header' class='accordian-header' data-tag='element-selector' data-accordian-content-selector='#element-selector-options'>
					add a form field 
				</div>
				<div id='element-selector-options'>
					{{for ~getWidgetTypes()}}						
						<div class='form-element {{:settings.klass}}' data-widget-type='{{:settings.klass}}' data-template-selector='{{:settings.template}}'>
							{{:settings.name}}
						</div>
					{{/for}}																			
				</div>				
			</div>
		{% endjsrender %}
		
		<!-- form element templates follow --> 
		
		<!-- common elements -->
		{% jsrender widget-common-label %}
			<div class='jq-label label-wrap'>
				<label {{if required}}class='required'{{/if}}><span class='jq-label-text'>{{> label }}</span><span class='required'>*</span></label>
			</div>
		{% endjsrender %}
		
		{% jsrender widget-common-helptext %}
			<div class='jq-help-text helptext-wrap'>
				{{> help_text }}
			</div>
		{% endjsrender %}
		
		{% jsrender widget-common-footer %}
			<div class='clear-fix'></div>
		{% endjsrender %}
		
		<!-- common context menu stuff -->
		{% jsrender context-menu-common-header %}
			<div class='context-header context-option-group'>
				<div class='context-option'>
					<label>type</label>
					<select class='jq-header'>
						{{for ~getWidgetTypes()}}
							<option value='{{:settings.klass}}' data-template-selector='{{:settings.template}}'>{{:settings.name}}</option>							
						{{/for}}											
					</select>
				</div>
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-common-label %}
			<div class='context-option-group'>
				<div class='context-option label'>
					<label>label</label>
					<input type='text' class='jq-label' />
				</div>
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-common-default %}
			<div class='context-option-group'>
				<div class='context-option default'>
					<label>default</label>
					<input type='text' class='jq-default' />
				</div>
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-common-help %}
			<div class='context-option-group'>
				<div class='context-option help-text'>
					<label>Help Text</label>
					<textarea class='jq-help-text' />
				</div>
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-common-required %}
			<div class='context-option required'>
				<label>Required</label>
				<input type='checkbox' class='jq-required' />
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-common-size %}
			<div class='context-option size'>
				Size 
				<select class='jq-size'>
					<option value='s'>small</option>
					<option value='m'>medium</option>
					<option value='l'>large</option>
				</select>
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-content-type %}
			<div class='context-option-group'>
				<div class='context-option content-type'>
					Content Type
					<select class='jq-content-type'>
						<option value='text'>text</option>
						<option value='richtext'>rich text</option>
					</select>
				</div>
			</div>
		{% endjsrender %}
		
		{% jsrender context-menu-option-group %}
			{{for ~options}}
				{{include tmpl="#context-menu-option-group-row" ~index=#index /}}
			{{/for}}
			<div class='jq-add add-option'><i class='icon-plus-sign'></i></div>
		{% endjsrender %}
		
		{% jsrender context-menu-option-group-row %}			
			<div class='option-wrapper {{if ~allowSelection}}selectable{{/if}}'>				
				{{if ~allowSelection}}				
					{{if ~allowMultiple}}		
						<input type='checkbox' value='{{:~index}}' name='{{:~groupName}}' {{if selected}}checked='checked'{{/if}} />
					{{else}}
						<input type='radio' value='{{:~index}}' name='{{:~groupName}}' {{if selected}}checked='checked'{{/if}} />						
					{{/if}}
				{{/if}}
				<input type='text' value='{{>text}}' />
				<div class='jq-remove remove-option' data-index='{{:~index}}'><i class='icon-remove-sign'></i></div>
			</div>			
		{% endjsrender %}
		
		<!-- widget shared -->
		{% jsrender widget-controls %}
			<div class='controls'>
				<div class='duplicate jq-duplicate-widget'><i class='icon-copy' /></div>				
				<div class='remove jq-remove-widget'><i class='icon-remove-sign' /></div>						
			</div>			
		{% endjsrender %}
		
		{% jsrender ui-window %}
			<div id='dfb-ui-window-{{:window_id}}' class='ui-window {{:border_type}}'>						
				<i class='window-dismiss icon-remove-sign'></i>
				
				<div class='window-content'>
					{{:content}}
				</div>
				{{if show_buttons}}
					<div class='window-buttons'>
						<a href='#' class='button jq-yes'>yes</a>
						<a href='#' class='button red jq-no'>no</a>
					</div>
				{{/if}}
			</div>
		{% endjsrender %}
		
		{% for key, widget in widget_descriptors.items %}
			{% include widget.builder_template_path %}
		{% endfor %}
					
{% endblock %}

django_form_architect/templates/django_form_architect/index.html
{% extends 'django_form_architect/base.html' %}

{% block content %}
	<div class='thin-column'>
		
	</div>
	<div class='main-column wide'>
		<div class='list-view-header'>
			<h2>Form Library</h2>
			
						
			<a href='{% url 'django_form_architect.views.build' %}' class='header-button'>
				<i class='icon-plus'></i> <span>add new</span>
			</a>
			<div class='header-button'>
				<input type='text' class='filter' />
			</div>
		</div>
			{% for form in forms %}
				<div class='list-view-item'>					
					<div class='list-view-name'>{{form.name}}</div>
					<a href='{% url 'django_form_architect.views.build' form.pid %}' class='list-view-button'>edit</a>
					<a href='#' class='list-view-button'>responses</a>
					<a href='{% url 'django_form_architect.views.share' form.pid %}' class='list-view-button'>share</a>
					<div style='clear:both;'>&nbsp;</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

django_form_architect/templates/django_form_architect/share.html
{% extends 'django_form_architect/base.html' %}

{% block content %}
	<div class='thin-column'>
		
	</div>
	<div class='main-column wide'>
		sharing!
	</div>
{% endblock %}